#!/usr/bin/env python

from models.match import Match
from models.opponent import Opponent
from cli import Cli

Opponent.create_table()
Match.create_table()

# DEVELOPMENT PURPOSES ONLY**
# Match.drop_table()
# Opponent.drop_table()

Opponent.get_all()
Match.get_all()

Cli().run()
